analysis.c:33: Warning: unreachable code
analysis.c:38: Warning: unreachable code
analysis.c:47: Warning: unreachable code
analysis.c:65: Warning: unreachable code
analysis.c:70: Warning: unreachable code
analysis.c:79: Warning: unreachable code
analysis.c:85: Warning: control falls off end of non-void function
analysis.c:91: Warning: function returns both with and without a value

Compilation Successful (8 warnings)
