char.c:5: unterminated character constant
char.c:11: unterminated character constant
char.c:2: Warning: ignoring extra characters at end of char constant '\asdf'
char.c:3: invalid char constant '\ss', treating as 'X'
char.c:4: explicit hex character (\x) out of range
char.c:5: Unmatched '
char.c:7: Warning: ignoring extra characters at end of char constant 'sr'
char.c:8: Warning: ignoring extra characters at end of char constant '\2344'
char.c:9: Warning: ignoring extra characters at end of char constant '\2g'
char.c:10: expecting hex digits after \x
char.c:11: Unmatched '
char.c:13: invalid char constant '\81', treating as 'X'
char.c:14: Warning: ignoring extra characters at end of char constant '\x2h'

Compilation Failed: 6 errors, 5 warnings
