const.c:21: operand must be modifiable lvalue: op ++
const.c:23: operand must be modifiable lvalue: op ++
const.c:24: operand must be modifiable lvalue: op ++
const.c:28: left operand must be modifiable lvalue: op =
const.c:29: left operand must be modifiable lvalue: op =
const.c:32: left operand must be modifiable lvalue: op =
const.c:34: left operand must be modifiable lvalue: op =
const.c:38: operand must be modifiable lvalue: op ++

Compilation Failed: 8 errors, 0 warnings
