old.c:8: illegal storage class for parameter `d'
old.c:7: declaration for nonexistent parameter `g'
old.c:8: multiple declarations for parameter `d'
old.c:5: Warning: parameter `b' defaults to signed int
old.c:5: Warning: parameter `c' defaults to signed int
old.c:5: formal `c' used multiple times
old.c:11: Warning: `duh' shadows previous declaration
	Previous declaration: old.c:3
old.c:11: Warning: `Duh' shadows previous declaration
	Previous declaration: old.c:3
old.c:11: Warning: unused variable `Duh'
old.c:17: illegal storage class for parameter `a'
old.c:20: parse error
old.c:20: declaration without a variable
old.c:21: Warning: `q' shadows previous declaration
	Previous declaration: old.c:17
old.c:21: parse error
old.c:21: variable `b' redeclared
old.c:22: extern `p' redeclared
	Previous declaration: old.c:5
old.c:23: undeclared variable `hello'
old.c:23: undeclared variable `there'
old.c:23: Warning: implicitly declaring function to return int: printf()
old.c:21: Warning: unused variable `b'
old.c:21: Warning: unused variable `q'
old.c:19: Warning: unused variable `c'

Compilation Failed: 12 errors, 10 warnings
