sdcls.c:10: Warning: struct/union/enum tag `empty' shadows previous declaration
	Previous declaration: sdcls.c:2
sdcls.c:11: Warning: struct/union/enum tag `empty2' shadows previous declaration
	Previous declaration: sdcls.c:6
sdcls.c:35: Warning: struct/union/enum tag `uempty' shadows previous declaration
	Previous declaration: sdcls.c:27
sdcls.c:36: Warning: struct/union/enum tag `uempty2' shadows previous declaration
	Previous declaration: sdcls.c:31
sdcls.c:20: undefined struct/union member: "test"
sdcls.c:20: cannot assign to incompatible struct/union
sdcls.c:55: Can't compute size of undimensioned array

Compilation Failed: 3 errors, 4 warnings
