signed.c:13: Warning: pointer base types have different sign
signed.c:16: Warning: pointer base types have different sign
signed.c:17: Warning: pointer base types have different sign
signed.c:18: Warning: pointer base types have different sign
signed.c:19: Warning: pointer base types have different sign
signed.c:21: Warning: pointer base types have different sign
signed.c:22: Warning: pointer base types have different sign

Compilation Successful (7 warnings)
