tq.c:17: cannot assign pointers with different base types
tq.c:20: cannot assign pointers with different base types
tq.c:21: cannot assign pointers with different base types
tq.c:22: cannot assign pointers with different base types
tq.c:24: cannot assign pointers with different base types
tq.c:26: cannot assign pointers with different base types
tq.c:27: cannot assign pointers with different base types

Compilation Failed: 7 errors, 0 warnings
